export const SET_COUNTRY = "SET_COUNTRY";

export const SET_FREELANCER_PROFILE = "SET_FREELANCER_PROFILE";

export const SET_FREELANCER_SKILLS = "SET_FREELANCER_SKILLS";

export const SET_DELETE_EXPRIENCE = "SET_DELETE_EXPRIENCE";

export const SET_DELETE_EDUCATION = "SET_DELETE_EDUCATION";

export const SET_DEGREE_LIST = "SET_DEGREE_LIST";

export const SET_EDIT_FREELANCER_INFO = "SET_EDIT_FREELANCER_INFO";

export const SET_EDIT_LANGUAGE = "SET_EDIT_LANGUAGE";

export const SET_EDIT_FREELANCER_LOCATION = "SET_EDIT_FREELANCER_LOCATION";

export const SET_ADD_EXPRIENCE = "SET_ADD_EXPRIENCE";

export const SET_CLIENT_INFO_DETAILS = "SET_CLIENT_INFO_DETAILS";

export const FORGOT_PASS_ERROR = "FORGOT_PASS_ERROR";

export const FORGOT_OTP_ERROR = "FORGOT_OTP_ERROR";

export const SET_INDUSTRIES_LIST = "SET_INDUSTRIES_LIST";

export const SET_TIMEZONE_LIST = "SET_TIMEZONE_LIST";

export const SET_EDIT_CLIENT_INFO = "SET_EDIT_CLIENT_INFO";

export const SET_CLOSE_ACCOUNT_REASON_LIST = "SET_CLOSE_ACCOUNT_REASON_LIST";

export const SET_ONLINE_STATUS = "SET_ONLINE_STATUS";

export const SET_LANGUAGE_LIST = "SET_LANGUAGE_LIST";

export const SET_HWP_LIST = "SET_HWP_LIST";

export const SET_HOURS_PER_WEEK = "SET_HOURS_PER_WEEK";

export const SET_EDIT_SKILLS = "SET_EDIT_SKILLS";

export const SET_EDIT_CERTIFICATE = "SET_EDIT_CERTIFICATE";

export const SET_DELETE_CERTIFICATE = "SET_DELETE_CERTIFICATE";

export const SET_PROFILE_IMG_CHANGE = "SET_PROFILE_IMG_CHANGE";

export const SET_EDIT_EDUCATION = "SET_EDIT_EDUCATION";

export const SET_EDIT_DESIGNATION = "SET_EDIT_DESIGNATION";

export const SET_EDIT_PORTFOLIO = "SET_EDIT_PORTFOLIO";

export const APPLE_SIGN_IN_FAIL = "APPLE_SIGN_IN_FAIL";

export const GOOGLE_SIGN_IN_FAIL = "GOOGLE_SIGN_IN_FAIL";

export const SET_EDIT_VIDEO = "SET_EDIT_VIDEO";

export const SET_VISIBLITY = "SET_VISIBLITY";

export const SET_EXPRIENCE_LEVEL = "SET_EXPRIENCE_LEVEL";

export const SET_DELETE_PORTFOLIO = "SET_DELETE_PORTFOLIO";

export const SET_ADDITIONAL_ACCOUNT = "SET_ADDITIONAL_ACCOUNT";

export const SET_SUBMIT_VERIF_DOCS = "SET_SUBMIT_VERIF_DOCS";

export const REQUEST_TESTIMONIAL = "REQUEST_TESTIMONIAL";

export const GET_TESTIMONIAL = "GET_TESTIMONIAL";

export const SET_JOB_DATA_LISTING = "SET_JOB_DATA_LISTING";

export const SET_CATEGORY_LIST = "SET_CATEGORY_LIST";

export const LOGIN_ERROR = "LOGIN_ERROR";

export const SIGNUP_ERROR = "SIGNUP_ERROR";

// JOB Types ----------------------------------------

export const JOBS_LIST = "JOBS_LIST";

export const SAVED_JOBS_LIST = "SAVED_JOBS_LIST";

export const SAVE_JOB_POST = "SAVE_JOB_POST";

export const UNSAVE_JOB_POST = "UNSAVE_JOB_POST";

export const JOB_POST_DETAILS = "JOB_POST_DETAILS";

export const SEND_PROPOSAL_DATA = "SEND_PROPOSAL_DATA";

export const SEND_JOB_PROPOSAL = "SEND_JOB_PROPOSAL";

export const DISLIKE_POST_REASONS = "DISLIKE_POST_REASONS";

export const ON_DISLIKE_JOB_POST = "ON_DISLIKE_JOB_POST";

export const SET_ALL_CLIENT_DRAFT_POSTING = "SET_ALL_CLIENT_DRAFT_POSTING";

export const SET_ALL_CLIENT_POSTING = "SET_ALL_CLIENT_POSTING";

export const SET_POST_YOUR_JOB_NOW = "SET_POST_YOUR_JOB_NOW";

export const SET_ALL_PROPOSALS = "SET_ALL_PROPOSALS";

export const SET_ALL_CONTRACTS = "SET_ALL_CONTRACTS";

export const SET_CLOSE_JOB_REASON_LIST = "SET_CLOSE_JOB_REASON_LIST";

export const SET_PORTFOLIO_ERROR = "SET_PORTFOLIO_ERROR";
