export const HOME_PAGE_DATA = "HOME_PAGE_DATA";

export const SET_COUNTRY = "SET_COUNTRY";

export const SET_FREELANCER_PROFILE = "SET_FREELANCER_PROFILE";

export const SET_FREELANCER_SKILLS = "SET_FREELANCER_SKILLS";

export const SET_DELETE_EXPRIENCE = "SET_DELETE_EXPRIENCE";

export const SET_DELETE_EDUCATION = "SET_DELETE_EDUCATION";

export const SET_DEGREE_LIST = "SET_DEGREE_LIST";

export const SET_EDIT_FREELANCER_INFO = "SET_EDIT_FREELANCER_INFO";

export const SET_EDIT_LANGUAGE = "SET_EDIT_LANGUAGE";

export const SET_EDIT_FREELANCER_LOCATION = "SET_EDIT_FREELANCER_LOCATION";

export const SET_ADD_EXPRIENCE = "SET_ADD_EXPRIENCE";

export const SET_CLIENT_INFO_DETAILS = "SET_CLIENT_INFO_DETAILS";

export const FORGOT_PASS_ERROR = "FORGOT_PASS_ERROR";

export const FORGOT_OTP_ERROR = "FORGOT_OTP_ERROR";

export const SET_INDUSTRIES_LIST = "SET_INDUSTRIES_LIST";

export const SET_TIMEZONE_LIST = "SET_TIMEZONE_LIST";

export const SET_EDIT_CLIENT_INFO = "SET_EDIT_CLIENT_INFO";

export const SET_CLOSE_ACCOUNT_REASON_LIST = "SET_CLOSE_ACCOUNT_REASON_LIST";

export const SET_ONLINE_STATUS = "SET_ONLINE_STATUS";

export const SET_LANGUAGE_LIST = "SET_LANGUAGE_LIST";

export const SET_HWP_LIST = "SET_HWP_LIST";

export const SET_HOURS_PER_WEEK = "SET_HOURS_PER_WEEK";

export const SET_EDIT_SKILLS = "SET_EDIT_SKILLS";

export const SET_EDIT_CERTIFICATE = "SET_EDIT_CERTIFICATE";

export const SET_DELETE_CERTIFICATE = "SET_DELETE_CERTIFICATE";

export const SET_PROFILE_IMG_CHANGE = "SET_PROFILE_IMG_CHANGE";

export const SET_EDIT_EDUCATION = "SET_EDIT_EDUCATION";

export const SET_EDIT_DESIGNATION = "SET_EDIT_DESIGNATION";

export const SET_EDIT_PORTFOLIO = "SET_EDIT_PORTFOLIO";

export const APPLE_SIGN_IN_FAIL = "APPLE_SIGN_IN_FAIL";

export const GOOGLE_SIGN_IN_FAIL = "GOOGLE_SIGN_IN_FAIL";

export const SET_EDIT_VIDEO = "SET_EDIT_VIDEO";

export const SET_VISIBLITY = "SET_VISIBLITY";

export const SET_EXPRIENCE_LEVEL = "SET_EXPRIENCE_LEVEL";

export const SET_DELETE_PORTFOLIO = "SET_DELETE_PORTFOLIO";

export const SET_ADDITIONAL_ACCOUNT = "SET_ADDITIONAL_ACCOUNT";

export const SET_SUBMIT_VERIF_DOCS = "SET_SUBMIT_VERIF_DOCS";

export const REQUEST_TESTIMONIAL = "REQUEST_TESTIMONIAL";

export const GET_TESTIMONIAL = "GET_TESTIMONIAL";

export const SET_JOB_DATA_LISTING = "SET_JOB_DATA_LISTING";

export const SET_CATEGORY_LIST = "SET_CATEGORY_LIST";

export const LOGIN_ERROR = "LOGIN_ERROR";

export const SIGNUP_ERROR = "SIGNUP_ERROR";

// JOB Types ----------------------------------------

export const JOBS_LIST = "JOBS_LIST";

export const SAVED_JOBS_LIST = "SAVED_JOBS_LIST";

export const SAVE_JOB_POST = "SAVE_JOB_POST";

export const UNSAVE_JOB_POST = "UNSAVE_JOB_POST";

export const JOB_POST_DETAILS = "JOB_POST_DETAILS";

export const SEND_PROPOSAL_DATA = "SEND_PROPOSAL_DATA";

export const SEND_JOB_PROPOSAL = "SEND_JOB_PROPOSAL";

export const DISLIKE_POST_REASONS = "DISLIKE_POST_REASONS";

export const ON_DISLIKE_JOB_POST = "ON_DISLIKE_JOB_POST";

export const SET_ALL_CLIENT_DRAFT_POSTING = "SET_ALL_CLIENT_DRAFT_POSTING";

export const SET_ALL_CLIENT_POSTING = "SET_ALL_CLIENT_POSTING";

export const SET_POST_YOUR_JOB_NOW = "SET_POST_YOUR_JOB_NOW";

export const SET_ALL_PROPOSALS = "SET_ALL_PROPOSALS";

export const SET_ALL_CONTRACTS = "SET_ALL_CONTRACTS";

export const SET_CLOSE_JOB_REASON_LIST = "SET_CLOSE_JOB_REASON_LIST";

export const SET_PORTFOLIO_ERROR = "SET_PORTFOLIO_ERROR";

export const FOOTER_PAGE_DATA = "FOOTER_PAGE_DATA";

export const VERIFY_OTP_ERROR = "VERIFY_OTP_ERROR";

export const VERIFY_SIGNUP_ERROR = "VERIFY_SIGNUP_ERROR";

export const RESEND_OTP_SUCCESS = "RESEND_OTP_SUCCESS";

export const CATEGORY_SKILL_DATA = "CATEGORY_SKILL_DATA";

export const SKILLS_DEVELOPER_DATA = "SKILLS_DEVELOPER_DATA";

export const INSTANT_LOGIN_EMAIL = "INSTANT_LOGIN_EMAIL";

export const ADD_CATEGORY = "ADD_CATEGORY";

export const HOURLY_PRICE = "HOURLY_PRICE";

export const SET_UPDATE_JOB_POST = "SET_UPDATE_JOB_POST";

export const SET_REMOVE_JOB_POST = "SET_REMOVE_JOB_POST";
export const SET_SINGLE_PROPOSAL_DETAILS = "SET_SINGLE_PROPOSAL_DETAILS";
export const DECLINE_REASONS_LIST = "DECLINE_REASONS_LIST";
export const PROPOSAL_TERMS_CHANGE = "PROPOSAL_TERMS_CHANGE";

// SUBSCRIPTION TYPES
export const SET_SUBSCRIPTION_LIST = "SET_SUBSCRIPTION_LIST";

export const SET_JOB_BASED_FREELANCER_LIST = "SET_JOB_BASED_FREELANCER_LIST";

export const SET_SAVED_TALENT_LIST = "SET_SAVED_TALENT_LIST";

export const SET_SAVED_TALENT = "SET_SAVED_TALENT";

export const SET_REMOVE_SAVED_TALENT = "SET_REMOVE_SAVED_TALENT";

export const SET_INVITED_FREELANCER_LIST = "SET_INVITED_FREELANCER_LIST";

export const SET_FREELANCER_INVITED = "SET_FREELANCER_INVITED";

export const SET_MAKE_PRIVATE_JOB = "SET_MAKE_PRIVATE_JOB";

export const SET_ALL_JOB_PROPOSALS_LIST = "SET_ALL_JOB_PROPOSALS_LIST";

export const SET_SAVE_PROPOSAL_IN_SHORTLIST = "SET_SAVE_PROPOSAL_IN_SHORTLIST";

export const SET_REMOVE_PROPOSAL_IN_SHORTLIST =
  "SET_REMOVE_PROPOSAL_IN_SHORTLIST";

export const SET_PROPOSAL_SHORTLIST = "SET_PROPOSAL_SHORTLIST";

export const SET_ARCHIEVED_LIST = "SET_ARCHIEVED_LIST";

export const SET_SAVE_PROPOSAL_IN_ARCHIEVED = "SET_SAVE_PROPOSAL_IN_ARCHIEVED";

export const SET_REMOVE_PROPOSAL_IN_ARCHIEVED =
  "SET_REMOVE_PROPOSAL_IN_ARCHIEVED";

export const SET_SINGLE_FREELANCER = "SET_SINGLE_FREELANCER";
