export const SET_COUNTRY = "SET_COUNTRY";

export const SET_FREELANCER_PROFILE = "SET_FREELANCER_PROFILE";

export const SET_FREELANCER_SKILLS = "SET_FREELANCER_SKILLS";

export const SET_DELETE_EXPRIENCE = "SET_DELETE_EXPRIENCE";
export const SET_ADD_EXPRIENCE = "SET_ADD_EXPRIENCE";
